In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Tensorflow 2.0.0 Basics Review
## - tf variables
## - tf operations
## - tf keras API

In [2]:
import tensorflow as tf

In [314]:
'''
- check tensorflow and keras version
'''
print(f'Tensorflow GPU Version: {tf.__version__}')
print(f'Eager Execution is: {tf.executing_eagerly()}')
print(f'Keras Version: {tf.keras.__version__}')

Tensorflow GPU Version: 2.0.0
Eager Execution is: True
Keras Version: 2.2.4-tf


In [5]:
'''
- check GPU 
'''
var = tf.Variable([3,3])
if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
    print(f'Running on {var.device[-5:]}')
else:
    print('Runing on CPU')

from keras import backend as K
K.tensorflow_backend._get_available_gpus()

Running on GPU
GPU #0?
False
Running on CPU:0


Using TensorFlow backend.


['/job:localhost/replica:0/task:0/device:GPU:0']

# tf variables

In [62]:
'''
- Declare variables
'''
var = 56
tf1 = tf.Variable(var, dtype=tf.float32)
tf1.assign(5.6)
tf2 = tf.Variable([[0,4,5],[4,2,7],[7,8,9]])
print('tf1: ',tf1)
print('tf2: ',tf2)
print(f'tf1 iwth Numpy: {tf1.numpy()}')

tf1:  <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.6>
tf2:  <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 4, 5],
       [4, 2, 7],
       [7, 8, 9]], dtype=int32)>
tf1 iwth Numpy: 5.599999904632568


In [72]:
'''
- Declare Constants
'''
constantVar = tf.constant(568, dtype = tf.int16)
print(constantVar)
print(constantVar.numpy())

tf.Tensor(568, shape=(), dtype=int16)
568


In [86]:
'''
- Reshape a tensor
'''
var = tf.Variable([[2,3,4,5],[5,2,9,0],[3,1,2,4]], dtype=tf.float32)
print('var shape:',var.shape)
var1 = tf.reshape(var,(2,6))
print('var1 shape:',var1.shape)
var2 = tf.reshape(var, (1,12))
print('var2 shape:',var2.shape)
var3 = tf.reshape(var, (4,3))
print('var3 shape:',var3.shape)

var shape: (3, 4)
var1 shape: (2, 6)
var2 shape: (1, 12)
var3 shape: (4, 3)


In [43]:
'''
- tensor dimention
- tensor slice
- tensor cast numpy
- tensor slice
- tensor dtype
'''
var = tf.Variable([[[2,3,4,5],[5,2,9,0],[3,1,2,4]],[[0,30,40,50],[5,2,9,0],[3,1,2,4]],[[12,13,14,15],[5,2,9,0],[3,1,2,4]]], dtype=tf.float32)
print('var rank:',tf.rank(var))
var2 = var[0:2]
print('var2 slice:',var2)
print('var2 rank:',tf.rank(var2).numpy())
print('var2 size:',tf.size(var2).numpy())
print('var2 dtype:', var2.dtype)

var rank: tf.Tensor(3, shape=(), dtype=int32)
var2 slice: tf.Tensor(
[[[ 2.  3.  4.  5.]
  [ 5.  2.  9.  0.]
  [ 3.  1.  2.  4.]]

 [[ 0. 30. 40. 50.]
  [ 5.  2.  9.  0.]
  [ 3.  1.  2.  4.]]], shape=(2, 3, 4), dtype=float32)
var2 rank: 3
var2 size: 24
var2 dtype: <dtype: 'float32'>


In [53]:
'''
- tensor element-wise primitive tensor operations
- tensor broadcasting
'''
var1 = tf.Variable([[[2,3,4,5],[5,2,9,0],[3,1,2,4]],[[0,30,40,50],[5,2,9,0],[3,1,2,4]],[[12,13,14,15],[5,2,9,0],[3,1,2,4]]], dtype=tf.float32)
var2 = tf.Variable([[[2,2,2,2],[2,2,2,2],[2,2,2,2]],[[2,2,2,2],[2,2,2,2],[2,2,2,2]],[[2,2,2,2],[2,2,2,2],[2,2,2,2]]], dtype=tf.float32)
var = var1 * var2
print('var tensor:\n',var)
print('\nvar numpy cast:\n',var.numpy())
print('\nvar*4:\n',var*4)

var tensor:
 tf.Tensor(
[[[  4.   6.   8.  10.]
  [ 10.   4.  18.   0.]
  [  6.   2.   4.   8.]]

 [[  0.  60.  80. 100.]
  [ 10.   4.  18.   0.]
  [  6.   2.   4.   8.]]

 [[ 24.  26.  28.  30.]
  [ 10.   4.  18.   0.]
  [  6.   2.   4.   8.]]], shape=(3, 3, 4), dtype=float32)

var numpy cast:
 [[[  4.   6.   8.  10.]
  [ 10.   4.  18.   0.]
  [  6.   2.   4.   8.]]

 [[  0.  60.  80. 100.]
  [ 10.   4.  18.   0.]
  [  6.   2.   4.   8.]]

 [[ 24.  26.  28.  30.]
  [ 10.   4.  18.   0.]
  [  6.   2.   4.   8.]]]

var*4:
 tf.Tensor(
[[[ 16.  24.  32.  40.]
  [ 40.  16.  72.   0.]
  [ 24.   8.  16.  32.]]

 [[  0. 240. 320. 400.]
  [ 40.  16.  72.   0.]
  [ 24.   8.  16.  32.]]

 [[ 96. 104. 112. 120.]
  [ 40.  16.  72.   0.]
  [ 24.   8.  16.  32.]]], shape=(3, 3, 4), dtype=float32)


In [68]:
'''
- tensor multiplication
- tensor constant
- tensor constant cast
'''
var1 = tf.constant([[1,2,3],[4,5,3]])
var2 = tf.constant([[1,2,3],[4,5,3]])
var = tf.matmul(var1,tf.transpose(var2))
print('var:\n',var)
var = tf.cast(var, dtype=tf.float32)
print('\nvar dtype:', var.dtype)

var:
 tf.Tensor(
[[14 23]
 [23 50]], shape=(2, 2), dtype=int32)

var dtype: <dtype: 'float32'>


In [88]:
'''
- ragged tensors by constant
- ragged tensors by split_row
'''
ragged_tensor = tf.ragged.constant([[1,2,4],[],[3,4],[1]], dtype=tf.float32, name='ragged_tensor')
print(ragged_tensor)
print(ragged_tensor[0])
print(ragged_tensor[3])
ragged_tensor2 = tf.RaggedTensor.from_row_splits(values=[1,2,4,5,6,7,8], row_splits=[0,3,3,5,6,7])
print(ragged_tensor2)

<tf.RaggedTensor [[1.0, 2.0, 4.0], [], [3.0, 4.0], [1.0]]>
tf.Tensor([1. 2. 4.], shape=(3,), dtype=float32)
tf.Tensor([1.], shape=(1,), dtype=float32)
<tf.RaggedTensor [[1, 2, 4], [], [5, 6], [7], [8]]>


# tf operations

In [106]:
'''
- calculate square differences
'''
t1 = tf.random.normal((3,1))
t2 = tf.random.normal((3,1))
t = tf.math.squared_difference(t1,t2,name='square_difference')
print('_t1:\n',t1)
print('_t2:\n',t2)
print('_t:\n',t)

_t1:
 tf.Tensor(
[[0.23302452]
 [0.33036613]
 [0.07002912]], shape=(3, 1), dtype=float32)
_t2:
 tf.Tensor(
[[-1.1006709 ]
 [-0.40500164]
 [-1.2100329 ]], shape=(3, 1), dtype=float32)
_t:
 tf.Tensor(
[[1.7787435 ]
 [0.54076576]
 [1.638559  ]], shape=(3, 1), dtype=float32)


In [180]:
'''
- calculate tensor mean
'''
var = tf.constant(tf.random.uniform((3,3),minval=0, maxval= 10, dtype=tf.float32))
cross_mean = tf.reduce_mean(var, axis=None)
x_mean = tf.reduce_mean(var, axis=0)
y_mean = tf.reduce_mean(var, axis=1)
x_mean_dim = tf.reduce_mean(var, axis=0,keepdims=True)
y_mean_dim = tf.reduce_mean(var, axis=1, keepdims=True)
print('_var:\n',var)
print('\n_cross_mean:\n',cross_mean)
print('\n_x_mean:\n',x_mean)
print('\n_x_mean_same_dim:\n',x_mean_dim)
print('\n_y_mean:\n',y_mean)
print('\n_y_mean_same_dim:\n',y_mean_dim)

_var:
 tf.Tensor(
[[8.844145   8.424911   5.7227373 ]
 [4.715581   8.562659   7.411667  ]
 [0.57933927 8.567917   4.0922523 ]], shape=(3, 3), dtype=float32)

_cross_mean:
 tf.Tensor(6.324579, shape=(), dtype=float32)

_x_mean:
 tf.Tensor([4.7130218 8.518496  5.7422185], shape=(3,), dtype=float32)

_x_mean_same_dim:
 tf.Tensor([[4.7130218 8.518496  5.7422185]], shape=(1, 3), dtype=float32)

_y_mean:
 tf.Tensor([7.6639304 6.8966355 4.4131694], shape=(3,), dtype=float32)

_y_mean_same_dim:
 tf.Tensor(
[[7.6639304]
 [6.8966355]
 [4.4131694]], shape=(3, 1), dtype=float32)


In [168]:
'''
- tensors with random normal values
'''
tf.random.set_seed(2)
var_random1 = tf.random.normal((4,1),mean=0,stddev=1)
var_random2 = tf.random.normal((4,1),mean=5,stddev=10)
print('_random_var1:\n',var_random1)
print('_random_var2:\n',var_random2)

_random_var1:
 tf.Tensor(
[[ 0.43616885]
 [-1.9093795 ]
 [ 1.3789066 ]
 [-1.0405852 ]], shape=(4, 1), dtype=float32)
_random_var2:
 tf.Tensor(
[[ 4.6377807]
 [14.660629 ]
 [-6.065405 ]
 [ 7.9940577]], shape=(4, 1), dtype=float32)


In [187]:
'''
- tensors with random uniform values
'''
tf.random.set_seed(2)
var1 = tf.random.uniform((4,1),minval=1, maxval=4, dtype=tf.int32)
var2 = tf.random.uniform((4,1),minval=5, maxval=8, dtype=tf.int32)
var_concat_x = tf.concat(values=[var1,var2],axis=0)
var_concat_y = tf.concat(values=[var1,var2],axis=1)
print('_var1:',var1)
print('_var2:',var2)
print('_var_concat_x:',var_concat_x)
print('_var_concat_y:',var_concat_y)

_var1: tf.Tensor(
[[3]
 [1]
 [3]
 [1]], shape=(4, 1), dtype=int32)
_var2: tf.Tensor(
[[7]
 [5]
 [7]
 [7]], shape=(4, 1), dtype=int32)
_var_concat_x: tf.Tensor(
[[3]
 [1]
 [3]
 [1]
 [7]
 [5]
 [7]
 [7]], shape=(8, 1), dtype=int32)
_var_concat_y: tf.Tensor(
[[3 7]
 [1 5]
 [3 7]
 [1 7]], shape=(4, 2), dtype=int32)


In [233]:
'''
- indexing tensor values
- defualt axis=None, it's across cols to search max or min
'''
tf.random.set_seed(1)
var = tf.constant(tf.random.uniform((10,10), minval=-2, maxval=10, dtype=tf.int32))
_max_index_x = tf.argmax(input = var, axis=0, output_type=tf.int32)
_min_index_y = tf.argmin(input = var, axis=1, output_type=tf.int32)
print('_var:\n', var)
print('_max_index_x:\n',_max_index_x.numpy())
print('_min_index_y:\n',_min_index_y.numpy())

_var:
 tf.Tensor(
[[ 4  7  1  3  4  8  8  5  2  0]
 [ 6  4  0  9  4  3 -2  2  5 -1]
 [ 3  4  8  0 -1  5  0  8  4  7]
 [ 8  2  9  7  0  5  7  8  1  2]
 [ 3  1 -1  9 -2  5  2  7 -2  0]
 [ 3  8 -1 -2  8  1  5  7  5  6]
 [ 0  9 -2  3  8  3  4  0  4  0]
 [ 0  9  2  3  8  1  1  3  1  4]
 [-2  5  4  6 -2 -1  0  2  0  7]
 [-2  1  8  6 -2  4  3  6  4  0]], shape=(10, 10), dtype=int32)
_max_index_x:
 [3 6 3 1 5 0 0 2 1 2]
_min_index_y:
 [9 6 4 4 4 3 2 0 0 0]


In [326]:
'''
-?????????????????????//
- Checkpoint to restore and save tensors
- Checkpoint's constructor accepts keyword arguments whose values are types that contain trackable state, such as 
  ~`tf.keras.optimizers.Optimizer` implementations, 
  ~`tf.Variable`, 
  ~`tf.keras.Layer` implementations,
  ~`tf.keras.Model` implementations. 
  It saves these values with a checkpoint and maintains a `save_counter` for numbering checkpoints
'''
var = tf.Variable([[1,2],[3,4]])
checkpoint = tf.train.Checkpoint(var=var)
path = checkpoint.save('./tf_ckpts/')
var = var.assign([[3,3,],[5,5]])
checkpoint.restore(path)

In [343]:
'''
- tf.function(
    func=None, input_signature=None, autograph=True, experimental_implements=None,
    experimental_autograph_options=None, experimental_relax_shapes=False,
    experimental_compile=None
)

'''
def calc(x,y):
    return x**2*5+y
f1 = tf.function(test)
print(f1(2,3))

@tf.function
def calc_2(x,y):
    return x*6+y
print(calc_2(3,4))

tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)


# tf keras API

In [344]:
from tensorflow.keras import backend as K

In [353]:
'''
- declare a variable with backend
- Keras is a model-level library, providing high-level building blocks for developing deep learning models. It does not handle low-level operations such as tensor products, convolutions and so on itself. 
- Instead, it relies on a specialized, well optimized tensor manipulation library to do so, serving as the "backend engine" of Keras. Rather than picking one single tensor library and making the 
implementation of Keras tied to that library, Keras handles the problem in a modular way, and several different backend engines can be plugged seamlessly into Keras.
'''
var = K.constant([[1,2],[3,4]],dtype=tf.float16)
var

<tf.Tensor: id=4445, shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [362]:
'''
- tf.keras Functional API
'''
ipt = tf.keras.Input(shape=(10,))
opt = tf.keras.layers.Dense(10)(ipt)
opt = tf.keras.layers.BatchNormalization()(opt)
opt = tf.keras.layers.LeakyReLU()(opt)
model = tf.keras.models.Model(ipt, opt)
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         [(None, 10)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                110       
_________________________________________________________________
batch_normalization_3 (Batch (None, 10)                40        
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 10)                0         
Total params: 150
Trainable params: 130
Non-trainable params: 20
_________________________________________________________________


In [ ]:
'''
- tf.keras Model class
'''
